"""Pull a Slack *browser* token (``xoxc-``) and its ``d`` cookie (``xoxd-``) out
of a local **Firefox** profile — the credentials the Slack web client itself
uses, for your own account, with no Slack app.

Used by ``chatensemble import-slack``. Firefox may stay open (files are copied before
reading). The ``localConfig_v2`` blob is sometimes snappy-compressed; that path
needs ``cramjam`` (``uv sync --extra slack-cookie``).
"""

from __future__ import annotations

import configparser
import json
import re
import shutil
import sqlite3
import tempfile
from dataclasses import dataclass
from pathlib import Path

_PROFILE_ROOTS = (
    Path.home() / "Library/Application Support/Firefox",   # macOS
    Path.home() / ".mozilla/firefox",                      # Linux
    Path.home() / "AppData/Roaming/Mozilla/Firefox",       # Windows
)


class SlackCookieError(RuntimeError):
    """Anything that stops us producing a token + cookie."""


@dataclass
class Workspace:
    name: str
    domain: str
    token: str | None

    @property
    def label(self) -> str:
        return self.name or self.domain or "?"


# --------------------------------------------------------------------------- #
def find_firefox_profile(explicit: str | Path | None = None) -> Path:
    if explicit:
        p = Path(explicit).expanduser()
        if not p.is_dir():
            raise SlackCookieError(f"no such Firefox profile: {p}")
        return p
    for root in _PROFILE_ROOTS:
        ini = root / "profiles.ini"
        if not ini.is_file():
            continue
        cp = configparser.ConfigParser()
        cp.read(ini)
        for want in (
            lambda s: s.startswith("Install") and cp[s].get("Default"),
            lambda s: cp[s].get("Default") == "1" and cp[s].get("Path"),
            lambda s: cp[s].get("Path"),
        ):
            for sect in cp.sections():
                if want(sect):
                    key = "Default" if sect.startswith("Install") else "Path"
                    return root / cp[sect][key]
    raise SlackCookieError("could not locate a Firefox profile (pass --profile)")


def _connect_ro(path: Path) -> sqlite3.Connection:
    if not path.is_file():
        raise SlackCookieError(f"missing {path}\n(open app.slack.com in Firefox, then retry)")
    tmp = Path(tempfile.mkdtemp()) / path.name
    shutil.copy(path, tmp)
    return sqlite3.connect(f"file:{tmp}?mode=ro", uri=True)


def read_d_cookie(profile: Path) -> str:
    con = _connect_ro(profile / "cookies.sqlite")
    row = con.execute(
        "SELECT value FROM moz_cookies WHERE host LIKE '%slack.com' AND name='d' "
        "ORDER BY length(value) DESC LIMIT 1"
    ).fetchone()
    if not row:
        raise SlackCookieError("no 'd' cookie for slack.com — sign in with Firefox first")
    return row[0]


def read_workspaces(profile: Path) -> list[Workspace]:
    ls = profile / "storage/default/https+++app.slack.com/ls/data.sqlite"
    con = _connect_ro(ls)
    row = con.execute(
        "SELECT compression_type, value FROM data WHERE key='localConfig_v2'"
    ).fetchone()
    if not row:
        raise SlackCookieError("localConfig_v2 not found — open app.slack.com in Firefox")
    ctype, val = row
    if ctype:
        try:
            import cramjam
        except ImportError as e:
            raise SlackCookieError(
                "the Slack config blob is compressed; run:  uv sync --extra slack-cookie"
            ) from e
        val = bytes(cramjam.snappy.decompress_raw(val))
    text = val.decode("utf-8", "replace") if isinstance(val, bytes) else val

    try:
        teams = json.loads(text).get("teams", {}).values()
    except json.JSONDecodeError:
        toks = sorted(set(re.findall(r"xoxc-[\w-]+", text)))
        return [Workspace(f"(token {i + 1})", "", t) for i, t in enumerate(toks)]

    out = []
    for t in teams:
        dom = (t.get("url") or t.get("domain") or "").replace("https://", "").rstrip("/")
        out.append(Workspace(t.get("name") or dom, dom, t.get("token")))
    return out


def pick_workspace(workspaces: list[Workspace], query: str | None) -> Workspace:
    cands = [w for w in workspaces if w.token]
    if query:
        q = query.lower()
        cands = [w for w in cands if q in (w.name + w.domain).lower()]
    if not cands:
        raise SlackCookieError(
            f"no signed-in Slack workspace{f' matching {query!r}' if query else ''}"
        )
    if len(cands) > 1:
        raise SlackCookieError(
            "ambiguous — narrow with --workspace: " + ", ".join(w.label for w in cands)
        )
    return cands[0]


def write_account_yaml(path: Path, token: str, cookie: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# generated by `chatensemble import-slack` — treat as a password\n"
        "type: slack\n"
        f"token: {token}\n"
        f"cookie: {cookie}\n"
    )
    path.chmod(0o600)
